input: "samplesheet.nfcore-molkart.csv"
outdir: "nfcore_molkart_output"
segmentation_method: "mesmer,cellpose,ilastik"
cellpose_save_flows: false
cellpose_diameter: 60
cellpose_chan: 0
cellpose_chan2: 1
cellpose_pretrained_model: "cyto"
cellpose_custom_model: CPx.Cellpose_MI_20230516_091551
cellpose_flow_threshold: 0.6
cellpose_edge_exclude: false
mesmer_image_mpp: 0.138
mesmer_compartment: "whole-cell"
ilastik_pixel_project: ilastik_pixelprob.ilp
ilastik_multicut_project: ilastik_multicut.tiff_save_model.ilp
tilesize: 2144
skip_clahe: false
clahe_cliplimit: 0.01
clahe_nbins: 256
clahe_pixel_size: 0.138
clahe_kernel: 25
create_training_subset: false
crop_amount: 4
crop_nonzero_fraction: 0.4
crop_size_x: 400
crop_size_y: 400
segmentation_min_area: 200
segmentation_max_area: 200000
